from pathlib import Path

import structlog

logger = structlog.get_logger(__name__)

class ObsidianManager:
    def __init__(self, vault_path: str):
        self.vault_path = Path(vault_path)
        self.folders = {
            "projects": self.vault_path / "Projects",
            "agents": self.vault_path / "Agents",
            "daily": self.vault_path / "Daily",
            "knowledge": self.vault_path / "Knowledge Base",
            "research": self.vault_path / "Research",
            "evolution": self.vault_path / "Evolution",
            "sandbox": self.vault_path / "Sandbox",
        }
        
        # Subdirectories
        self.subdirs = [
            self.folders["knowledge"] / "verified",
            self.folders["knowledge"] / "experimental",
            self.folders["knowledge"] / "deprecated",
            self.folders["research"] / "inbox",
            self.folders["research"] / "verified",
            self.folders["research"] / "experiments",
            self.folders["research"] / "rejected",
            self.folders["research"] / "deprecated",
            self.folders["evolution"] / "failures",
            self.folders["sandbox"] / "experiments",
            self.folders["sandbox"] / "coding-challenges",
            self.folders["sandbox"] / "benchmarks",
            self.folders["sandbox"] / "prototypes",
            self.folders["sandbox"] / "failed-attempts",
        ]

    def init_vault(self):
        """Creates the base folder structure for the Obsidian vault."""
        self.vault_path.mkdir(parents=True, exist_ok=True)
        for folder in self.folders.values():
            folder.mkdir(exist_ok=True)
        for subdir in self.subdirs:
            subdir.mkdir(parents=True, exist_ok=True)
            
        # Create a welcome/index note
        index_path = self.vault_path / "EvoForge Index.md"
        if not index_path.exists():
            with open(index_path, "w", encoding="utf-8") as f:
                f.write("# EvoForge System Index\n\nThis vault contains all semantic knowledge generated by EvoForge.\n")
        
        logger.info("obsidian_vault_initialized", path=str(self.vault_path))

    def write_project_note(self, repo_name: str, content: str, frontmatter: dict | None = None):
        """Writes or updates a project document in the vault."""
        note_path = self.folders["projects"] / f"{repo_name}.md"
        self._write_note(note_path, content, frontmatter)

    def write_daily_note(self, date_str: str, content: str):
        """Writes or updates a daily log note."""
        note_path = self.folders["daily"] / f"{date_str}.md"
        self._write_note(note_path, content)
        
    def write_agent_profile(self, agent_name: str, content: str, frontmatter: dict | None = None):
        """Writes or updates an agent profile note."""
        agent_dir = self.folders["agents"] / agent_name
        agent_dir.mkdir(parents=True, exist_ok=True)
        note_path = agent_dir / "profile.md"
        self._write_note(note_path, content, frontmatter)
        
    def write_skill_note(self, agent_name: str, skill_name: str, content: str, frontmatter: dict | None = None):
        """Writes or updates a specific skill note for an agent."""
        skills_dir = self.folders["agents"] / agent_name / "skills"
        skills_dir.mkdir(parents=True, exist_ok=True)
        note_path = skills_dir / f"{skill_name}.md"
        self._write_note(note_path, content, frontmatter)

    def _write_note(self, path: Path, content: str, frontmatter: dict | None = None):
        """Helper to write a note with optional YAML frontmatter."""
        try:
            with open(path, "w", encoding="utf-8") as f:
                if frontmatter:
                    f.write("---\n")
                    f.writelines(f"{k}: {v}\n" for k, v in frontmatter.items())
                    f.write("---\n\n")
                f.write(content)
            logger.debug("note_written", file=path.name)
        except Exception as e:
            logger.error("note_write_failed", file=path.name, error=str(e))
            raise

    def read_note(self, relative_path: str) -> str | None:
        """Reads a note's raw content."""
        path = self.vault_path / relative_path
        if not path.exists():
            return None
        try:
            with open(path, "r", encoding="utf-8") as f:
                return f.read()
        except Exception as e:
            logger.error("note_read_failed", file=relative_path, error=str(e))
            return None
