import os
import structlog
from pathlib import Path
from typing import Dict, List, Optional
from datetime import datetime

logger = structlog.get_logger(__name__)

class ObsidianManager:
    def __init__(self, vault_path: str):
        self.vault_path = Path(vault_path)
        self.folders = {
            "projects": self.vault_path / "Projects",
            "agents": self.vault_path / "Agents",
            "daily": self.vault_path / "Daily",
            "knowledge": self.vault_path / "Knowledge Base",
        }

    def init_vault(self):
        """Creates the base folder structure for the Obsidian vault."""
        self.vault_path.mkdir(parents=True, exist_ok=True)
        for folder in self.folders.values():
            folder.mkdir(exist_ok=True)
            
        # Create a welcome/index note
        index_path = self.vault_path / "EvoForge Index.md"
        if not index_path.exists():
            with open(index_path, "w", encoding="utf-8") as f:
                f.write("# EvoForge System Index\n\nThis vault contains all semantic knowledge generated by EvoForge.\n")
        
        logger.info("obsidian_vault_initialized", path=str(self.vault_path))

    def write_project_note(self, repo_name: str, content: str, frontmatter: Optional[Dict] = None):
        """Writes or updates a project document in the vault."""
        note_path = self.folders["projects"] / f"{repo_name}.md"
        self._write_note(note_path, content, frontmatter)

    def write_daily_note(self, date_str: str, content: str):
        """Writes or updates a daily log note."""
        note_path = self.folders["daily"] / f"{date_str}.md"
        self._write_note(note_path, content)
        
    def _write_note(self, path: Path, content: str, frontmatter: Optional[Dict] = None):
        """Helper to write a note with optional YAML frontmatter."""
        try:
            with open(path, "w", encoding="utf-8") as f:
                if frontmatter:
                    f.write("---\n")
                    for k, v in frontmatter.items():
                        f.write(f"{k}: {v}\n")
                    f.write("---\n\n")
                f.write(content)
            logger.debug("note_written", file=path.name)
        except Exception as e:
            logger.error("note_write_failed", file=path.name, error=str(e))
            raise

    def read_note(self, relative_path: str) -> Optional[str]:
        """Reads a note's raw content."""
        path = self.vault_path / relative_path
        if not path.exists():
            return None
        try:
            with open(path, "r", encoding="utf-8") as f:
                return f.read()
        except Exception as e:
            logger.error("note_read_failed", file=relative_path, error=str(e))
            return None
